# Runs tests that complete relatively quickly.
name: test

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - "**/Cargo.toml"
      - "**/*.rs"
      - .github/workflows/test.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  DEBIAN_FRONTEND: noninteractive
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  # Run non-integration tests. This should be quick.
  unit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.59.0-buster
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: ./.github/actions/install-protoc
      - run: |
          cargo test --all --no-run \
            --exclude=linkerd-app \
            --exclude=linkerd-app-admin \
            --exclude=linkerd-app-core \
            --exclude=linkerd-app-gateway \
            --exclude=linkerd-app-inbound \
            --exclude=linkerd-app-integration \
            --exclude=linkerd-app-outbound \
            --exclude=linkerd-app-test \
            --exclude=linkerd2-proxy
      - run: |
          cargo test --all \
            --exclude=linkerd-app \
            --exclude=linkerd-app-admin \
            --exclude=linkerd-app-core \
            --exclude=linkerd-app-gateway \
            --exclude=linkerd-app-inbound \
            --exclude=linkerd-app-integration \
            --exclude=linkerd-app-outbound \
            --exclude=linkerd-app-test \
            --exclude=linkerd2-proxy
